### ISSUE TITLE
Not working with current master of adapt_framework

### ISSUE THREAD

**Issue by chris-steele** [cgkineo/adapt-pageIncompletePrompt#11]
Selecting Yes or No has no effect. Same behaviour whether using navigation back button, URL, quicknav etc; an entry in the browser history is registered before the prompt is dismissed, which obviously shouldn't be happening.

**Comment by moloko** [comment]
yes this needs an update to the framework which @oliverfoster said he was going to do... have a look at notifyView.js in ken15244 if you need a quick fix

**Comment by chris-steele** [comment]
@moloko sure do, thanks!

**Comment by moloko** [comment]
should be sorted now, please re-open if you find otherwise
