### ISSUE TITLE
Alert pop-up - read error plus Yes and No buttons misread

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-pageIncompletePrompt#3]
_From @shauncg on October 28, 2014 16:14_

When the alert pops up to warn the user they haven't finished the page, JAWS stumbles over the word "Alert", making it sound like "aaaaaarrrlert" (sorry, not sure how else to describe this!). I'd guess that for whatever reason, generating this alert is momentarily resource heavy and JAWS struggles briefly. 

Also, when the Yes and No buttons are tabbed to, a similar issue to that described in Row 16 occurs: they are described as ""Accessibility underline test underline course underline 14 point 10 point 22 slash index link" followed by "yes" or "no" respectively. 

_Copied from original issue: cgkineo/adapt_framework#26_

**Comment by moloko** [comment]
still an issue?
