### ISSUE TITLE
Course closes unexpectedly

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-pageIncompletePrompt#34]
[This line](https://github.com/cgkineo/adapt-pageIncompletePrompt/blob/master/js/adapt-pageIncompletePrompt.js#L69) can cause the lms to close the window. It needs to change the hash only.

**Comment by moloko** [comment]
Note: doesn't always close the window - it causes the page to reload. which can cause some LMSes to close the course window. Either way, it's definitely not desirable!
