### ISSUE TITLE
add properties.schema to make compatible with authoring tool

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-pageIncompletePrompt#9]

**Comment by hmaffin** [comment]
Is uploadable to AT ok - can enable it but cog icon never appears on page. Is there anything else that needs turning on or being present in the course to make it work? I was just testing it on a simple one page course, and added an MCQ.

**Comment by moloko** [comment]
there's no properties.schema yet - hence this ticket ;-)

**Comment by hmaffin** [comment]
AH bugger sorry that was meant for the devtools one
